services:
  jarvis-bot:
    build: ./Jarvis-Java
    container_name: jarvis-bot
    environment:
      - GO_AGENT_URL=http://go-agent:8081/api/v1/chat
    restart: always
    volumes: 
    - jarvis_data:/shared_files

  db:
    image: postgres:16-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: jarvis_user
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: jarvis_db
    ports:
      - "5432:5432"  # Добавь эту строку!
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  
  go-agent:
    build: ./Jarvis-Go
    container_name: go-agent
    restart: always
    environment:
      - DB_URL=postgres://jarvis_user:secret_password@postgres-db:5432/jarvis_db?sslmode=disable
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    depends_on:
      - db
    volumes:
      - jarvis_data:/shared_files
      
volumes:
  jarvis_data: