# Этап 1: Сборка
FROM golang:1.26-alpine AS build
WORKDIR /app

# Копируем файлы зависимостей и скачиваем их
COPY go.mod go.sum* ./
RUN go mod download

# Копируем исходный код
COPY . .

# Собираем бинарник (CGO_ENABLED=0 для статической линковки)
RUN CGO_ENABLED=0 GOOS=linux go build -o main .

# Этап 2: Финальный легкий образ
FROM alpine:latest
WORKDIR /root/

# Копируем только готовый бинарный файл из первого этапа
COPY --from=build /app/main .

# Указываем порт, который слушает твой Go-сервер
EXPOSE 8081

# Запускаем приложение
CMD ["./main"]