bot:
  name: "jarvis_tackroy_bot" # Как ты назвал его в @BotFather
  token: "8629077876:AAFgX9tz2YHQy1VSrJZ7fi6C8EhX2Ae4ktM" # Токен, который дал @BotFather
go:
  agent:
    url: http://go-agent:8081/api/v1/chat
# Параметры подключения к БД
spring.datasource.url=jdbc:postgresql://postgres-db:5432/jarvis
spring.datasource.username=user
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver

# Чтобы Spring не падал, если база еще не поднялась
spring.datasource.hikari.initialization-fail-timeout=0