bot:
  name: "jarvis_tackroy_bot" # Как ты назвал его в @BotFather
  token: "8629077876:AAFgX9tz2YHQy1VSrJZ7fi6C8EhX2Ae4ktM" # Токен, который дал @BotFather
go:
  agent:
    url: http://go-agent:8081/api/v1/chat
spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/jarvis
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver